<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{1f4e1dbe-6536-433b-aa85-c20dffd35be3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
		//cmt1
		btest_1:BOOL;
		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>